[package]
name = "todo-actix"
version = "0.1.0"
authors = ["Eric Rochester <erochest@gmail.com>"]

[dependencies]
actix = "0.5.8"
actix-web = "0.6.13"
futures = "0.1.21"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
